steps:
  # Build the backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/footybets-backend', './backend']
    
  # Build the frontend  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/footybets-frontend', './frontend']
    
  # Push the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/footybets-backend']
    
  # Push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/footybets-frontend']
    
  # Deploy backend to Cloud Run (Australia Southeast 1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'footybets-backend',
      '--image', 'gcr.io/$PROJECT_ID/footybets-backend',
      '--region', 'australia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'DATABASE_URL=postgresql://footybets_user:footybets_password@34.40.170.58:5432/footybets,ENVIRONMENT=production,DEBUG=false',
      '--set-secrets', 'DATABASE_PASSWORD=db-password:latest,APP_SECRET_KEY=app-secret-key:latest,GEMINI_API_KEY=gemini-api-key:latest,API_SECRET_KEY=api-secret-key:latest'
    ]
    
  # Deploy frontend to Cloud Run (Australia Southeast 1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'footybets-frontend',
      '--image', 'gcr.io/$PROJECT_ID/footybets-frontend',
      '--region', 'australia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '5'
    ]

# Environment variables
substitutions:
  _REGION: 'australia-southeast1'
  _DATABASE_IP: '34.40.170.58'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'

timeout: '1200s' 