"""remove first_name and last_name columns

Revision ID: 6cbf6b98bc15
Revises: 
Create Date: 2025-07-26 22:30:26.684599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbf6b98bc15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_brownlow_votes_game_id', table_name='brownlow_votes')
    op.drop_index('idx_brownlow_votes_player_id', table_name='brownlow_votes')
    op.drop_index('idx_brownlow_votes_round', table_name='brownlow_votes')
    op.drop_index('idx_brownlow_votes_season', table_name='brownlow_votes')
    op.drop_table('brownlow_votes')
    op.drop_column('player_game_stats', 'brownlow_votes')
    op.add_column('user_tips', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_tips_user_id'), 'user_tips', ['user_id'], unique=False)
    op.create_foreign_key(None, 'user_tips', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'user_tips', type_='foreignkey')
    op.drop_index(op.f('ix_user_tips_user_id'), table_name='user_tips')
    op.drop_column('user_tips', 'user_id')
    op.add_column('player_game_stats', sa.Column('brownlow_votes', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.create_table('brownlow_votes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('votes', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('season', sa.INTEGER(), nullable=False),
    sa.Column('round_number', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brownlow_votes_season', 'brownlow_votes', ['season'], unique=False)
    op.create_index('idx_brownlow_votes_round', 'brownlow_votes', ['round_number'], unique=False)
    op.create_index('idx_brownlow_votes_player_id', 'brownlow_votes', ['player_id'], unique=False)
    op.create_index('idx_brownlow_votes_game_id', 'brownlow_votes', ['game_id'], unique=False)
    # ### end Alembic commands ###
