"""create missing tables

Revision ID: c8d6c58eb895
Revises: 6cbf6b98bc15
Create Date: 2025-07-28 11:43:48.493014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8d6c58eb895'
down_revision: Union[str, None] = '6cbf6b98bc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('content_structure', sa.JSON(), nullable=True),
    sa.Column('seo_template', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_templates_content_type'), 'content_templates', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_templates_created_by'), 'content_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_content_templates_id'), 'content_templates', ['id'], unique=False)
    op.create_index(op.f('ix_content_templates_name'), 'content_templates', ['name'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('afl_id', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals_kicked', sa.Integer(), nullable=True),
    sa.Column('behinds_kicked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_afl_id'), 'players', ['afl_id'], unique=True)
    op.create_index(op.f('ix_players_current_team_id'), 'players', ['current_team_id'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('behinds', sa.Integer(), nullable=True),
    sa.Column('kicks', sa.Integer(), nullable=True),
    sa.Column('handballs', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('hitouts', sa.Integer(), nullable=True),
    sa.Column('frees_for', sa.Integer(), nullable=True),
    sa.Column('frees_against', sa.Integer(), nullable=True),
    sa.Column('disposals', sa.Integer(), nullable=True),
    sa.Column('contested_possessions', sa.Integer(), nullable=True),
    sa.Column('uncontested_possessions', sa.Integer(), nullable=True),
    sa.Column('inside_50s', sa.Integer(), nullable=True),
    sa.Column('rebound_50s', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('clangers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_game_stats_game_id'), 'player_game_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_id'), 'player_game_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_player_id'), 'player_game_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_team_id'), 'player_game_stats', ['team_id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_context', sa.Text(), nullable=True),
    sa.Column('generation_parameters', sa.JSON(), nullable=True),
    sa.Column('related_game_id', sa.Integer(), nullable=True),
    sa.Column('related_team_id', sa.Integer(), nullable=True),
    sa.Column('related_prediction_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_content_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['related_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['related_prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['related_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_author_id'), 'content', ['author_id'], unique=False)
    op.create_index(op.f('ix_content_content_type'), 'content', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_created_by'), 'content', ['created_by'], unique=False)
    op.create_index(op.f('ix_content_expires_at'), 'content', ['expires_at'], unique=False)
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_index(op.f('ix_content_parent_content_id'), 'content', ['parent_content_id'], unique=False)
    op.create_index(op.f('ix_content_published_at'), 'content', ['published_at'], unique=False)
    op.create_index(op.f('ix_content_related_game_id'), 'content', ['related_game_id'], unique=False)
    op.create_index(op.f('ix_content_related_prediction_id'), 'content', ['related_prediction_id'], unique=False)
    op.create_index(op.f('ix_content_related_team_id'), 'content', ['related_team_id'], unique=False)
    op.create_index(op.f('ix_content_scheduled_at'), 'content', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=True)
    op.create_index(op.f('ix_content_title'), 'content', ['title'], unique=False)
    op.create_index(op.f('ix_content_updated_by'), 'content', ['updated_by'], unique=False)
    op.create_table('content_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('unique_views', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('engagement_time', sa.Float(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('scroll_depth', sa.Float(), nullable=True),
    sa.Column('click_through_rate', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('search_impressions', sa.Integer(), nullable=True),
    sa.Column('search_clicks', sa.Integer(), nullable=True),
    sa.Column('search_position', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_analytics_content_id'), 'content_analytics', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_analytics_date'), 'content_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_content_analytics_id'), 'content_analytics', ['id'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('generation_parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_content_id'), 'content_versions', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_versions_created_by'), 'content_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_content_versions_id'), 'content_versions', ['id'], unique=False)
    op.create_index(op.f('ix_content_versions_version_number'), 'content_versions', ['version_number'], unique=False)
    op.create_index(op.f('ix_analytics_id'), 'analytics', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_period_end'), 'analytics', ['period_end'], unique=False)
    op.create_index(op.f('ix_analytics_period_start'), 'analytics', ['period_start'], unique=False)
    op.drop_index('idx_games_date', table_name='games')
    op.drop_index('idx_games_season', table_name='games')
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_round_number'), 'games', ['round_number'], unique=False)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.drop_index('idx_predictions_game_id', table_name='predictions')
    op.create_index(op.f('ix_predictions_game_id'), 'predictions', ['game_id'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_predicted_winner_id'), 'predictions', ['predicted_winner_id'], unique=False)
    op.add_column('security_logs', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('security_logs', sa.Column('success', sa.Boolean(), nullable=True))
    op.drop_index('idx_security_logs_event_type', table_name='security_logs')
    op.drop_index('idx_security_logs_user_id', table_name='security_logs')
    op.create_index(op.f('ix_security_logs_id'), 'security_logs', ['id'], unique=False)
    op.drop_column('security_logs', 'event_data')
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('idx_teams_abbreviation', table_name='teams')
    op.drop_index('idx_teams_name', table_name='teams')
    op.drop_constraint('teams_abbreviation_key', 'teams', type_='unique')
    op.drop_constraint('teams_name_key', 'teams', type_='unique')
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.drop_index('idx_user_tips_game_id', table_name='user_tips')
    op.drop_index('idx_user_tips_user_id', table_name='user_tips')
    op.create_index(op.f('ix_user_tips_game_id'), 'user_tips', ['game_id'], unique=False)
    op.create_index(op.f('ix_user_tips_id'), 'user_tips', ['id'], unique=False)
    op.create_index(op.f('ix_user_tips_predicted_winner_id'), 'user_tips', ['predicted_winner_id'], unique=False)
    op.create_index(op.f('ix_user_tips_user_email'), 'user_tips', ['user_email'], unique=False)
    op.create_index(op.f('ix_user_tips_user_id'), 'user_tips', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_tips_user_name'), 'user_tips', ['user_name'], unique=False)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_user_tips_user_name'), table_name='user_tips')
    op.drop_index(op.f('ix_user_tips_user_id'), table_name='user_tips')
    op.drop_index(op.f('ix_user_tips_user_email'), table_name='user_tips')
    op.drop_index(op.f('ix_user_tips_predicted_winner_id'), table_name='user_tips')
    op.drop_index(op.f('ix_user_tips_id'), table_name='user_tips')
    op.drop_index(op.f('ix_user_tips_game_id'), table_name='user_tips')
    op.create_index('idx_user_tips_user_id', 'user_tips', ['user_id'], unique=False)
    op.create_index('idx_user_tips_game_id', 'user_tips', ['game_id'], unique=False)
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.create_unique_constraint('teams_name_key', 'teams', ['name'])
    op.create_unique_constraint('teams_abbreviation_key', 'teams', ['abbreviation'])
    op.create_index('idx_teams_name', 'teams', ['name'], unique=False)
    op.create_index('idx_teams_abbreviation', 'teams', ['abbreviation'], unique=False)
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('security_logs', sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_security_logs_id'), table_name='security_logs')
    op.create_index('idx_security_logs_user_id', 'security_logs', ['user_id'], unique=False)
    op.create_index('idx_security_logs_event_type', 'security_logs', ['event_type'], unique=False)
    op.drop_column('security_logs', 'success')
    op.drop_column('security_logs', 'details')
    op.drop_index(op.f('ix_predictions_predicted_winner_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_game_id'), table_name='predictions')
    op.create_index('idx_predictions_game_id', 'predictions', ['game_id'], unique=False)
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_round_number'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.create_index('idx_games_season', 'games', ['season'], unique=False)
    op.create_index('idx_games_date', 'games', ['game_date'], unique=False)
    op.drop_index(op.f('ix_analytics_period_start'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_period_end'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_id'), table_name='analytics')
    op.drop_index(op.f('ix_content_versions_version_number'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_created_by'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_content_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_content_analytics_id'), table_name='content_analytics')
    op.drop_index(op.f('ix_content_analytics_date'), table_name='content_analytics')
    op.drop_index(op.f('ix_content_analytics_content_id'), table_name='content_analytics')
    op.drop_table('content_analytics')
    op.drop_index(op.f('ix_content_updated_by'), table_name='content')
    op.drop_index(op.f('ix_content_title'), table_name='content')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.drop_index(op.f('ix_content_scheduled_at'), table_name='content')
    op.drop_index(op.f('ix_content_related_team_id'), table_name='content')
    op.drop_index(op.f('ix_content_related_prediction_id'), table_name='content')
    op.drop_index(op.f('ix_content_related_game_id'), table_name='content')
    op.drop_index(op.f('ix_content_published_at'), table_name='content')
    op.drop_index(op.f('ix_content_parent_content_id'), table_name='content')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index(op.f('ix_content_expires_at'), table_name='content')
    op.drop_index(op.f('ix_content_created_by'), table_name='content')
    op.drop_index(op.f('ix_content_content_type'), table_name='content')
    op.drop_index(op.f('ix_content_author_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_player_game_stats_team_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_player_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_game_id'), table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_current_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_afl_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_content_templates_name'), table_name='content_templates')
    op.drop_index(op.f('ix_content_templates_id'), table_name='content_templates')
    op.drop_index(op.f('ix_content_templates_created_by'), table_name='content_templates')
    op.drop_index(op.f('ix_content_templates_content_type'), table_name='content_templates')
    op.drop_table('content_templates')
    # ### end Alembic commands ###
